(ns smws_numbers.models.distillery_codes)

(def codes
  {
    "1" "Glenfarclas"
    "2" "The Glenlivet"
    "3" "Bowmore"
    "4" "Highland Park"
    "5" "Auchentoshan"
    "6" "Glen Deveron / Macduff"
    "7" "Longmorn"
    "8" "Tamdhu"
    "9" "Glen Grant"
    "10" "Bunnahabhain"
    "11" "Tomatin"
    "12" "Benriach"
    "13" "Dalmore"
    "14" "Talisker"
    "15" "Glenfiddich"
    "16" "Glenturret"
    "17" "Scapa"
    "18" "Inchgower"
    "19" "Glen Garioch"
    "20" "Inverleven (D)"
    "21" "Glenglassaugh"
    "22" "Glenkinchie"
    "23" "Bruichladdich"
    "24" "The Macallan"
    "25" "Rosebank"
    "26" "Clynelish"
    "27" "Springbank"
    "28" "Tullibardine"
    "29" "Laphroaig"
    "30" "Glenrothes"
    "31" "Isle of Jura"
    "32" "Edradour"
    "33" "Ardbeg"
    "34" "Tamnavulin"
    "35" "Glen Moray"
    "36" "Benrinnes"
    "37" "Cragganmore"
    "38" "Caperdonich"
    "39" "Linkwood"
    "40" "Balvenie"
    "41" "Dailuaine"
    "42" "Ledaig / Tobermory"
    "43" "Port Ellen (M)"
    "44" "Craigellachie"
    "45" "Dallas Dhu (C)"
    "46" "Glenlossie"
    "47" "Benromach"
    "48" "Balmenach"
    "49" "Linlithgow / St Magdalene (D)"
    "50" "Bladnoch"
    "51" "Bushmills"
    "52" "Old Pulteney"
    "53" "Caol Ila"
    "54" "Aberlour"
    "55" "Royal Brackla (C)"
    "56" "Coleburn (C)"
    "57" "Glen Mhor (D)"
    "58" "Strathisla"
    "59" "Teaninich"
    "60" "Aberfeldy"
    "61" "Brora"
    "62" "Glenochy"
    "63" "Glentauchers"
    "64" "Mannochmore"
    "65" "Imperial"
    "66" "Ardmore"
    "67" "Banff"
    "68" "Blair Athol"
    "69" "Glen Albyn"
    "70" "Balblair"
    "71" "Glenburgie / Glencraig (C)"
    "72" "Miltonduff (C)"
    "73" "Aultmore"
    "74" "North Port (C)"
    "75" "Glenury"
    "76" "Mortlach"
    "77" "Glen Ord / Glenordie"
    "78" "Ben Nevis"
    "79" "Deanston"
    "80" "Glen Spey"
    "81" "Glen Keith"
    "82" "Glencadam"
    "83" "Convalmore (C)"
    "84" "Glendullan"
    "85" "Glen Elgin"
    "86" "Glen Esk (M)"
    "87" "Millburn (D)"
    "88" "Speyburn"
    "89" "Tomintoul"
    "90" "Pittyvaich"
    "91" "Dufftown"
    "92" "Lochside"
    "93" "Glen Scotia"
    "94" "Fettercairn"
    "95" "Auchroisk"
    "96" "Glendronach"
    "97" "Littlemill"
    "98" "Lomond"
    "99" "Glenugie (C)"
    "100" "Strathmill"
    "101" "Knockando"
    "102" "Dalwhinnie"
    "103" "Royal Lochnagar"
    "104" "Glen Craig"
    "105" "Tormore"
    "106" "Cardhu"
    "107" "Glenallachie"
    "108" "Allt-a’Bhainne"
    "109" "Mosstowie"
    "110" "Oban"
    "111" "Lagavulin"
    "112" "Inchmurrin"
    "113" "Braes of Glenlivet"
    "114" "Longrow"
    "115" "Knockdhu"
    "116" "Nikka Distilleries (Japan)"
    "117" "Cooley (Ireland)"
    "118" "Connemara (Ireland)" })

(defn search-by-number [search-string]
    (filter #(= search-string (first %1)) codes))

(defn search-by-name [search-string]
    (filter #(re-find (re-pattern (.toLowerCase search-string)) (.toLowerCase (second %1))) codes))


